import { db, storage } from "./firebase.js";
import { watchAuth } from "./auth.js";
import { collection,getDocs,query,where } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import { ref,uploadBytesResumable,getDownloadURL } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-storage.js";
let adminUser=null;const clean=v=>String(v??"").trim();
watchAuth(({user,profile})=>{if(user&&profile?.role==="admin")adminUser=user});
async function uploadMedia(){const file=document.getElementById("mediaFile")?.files?.[0],folder=clean(document.getElementById("mediaFolder")?.value),out=document.getElementById("mediaUrlOutput"),msg=document.getElementById("mediaMessage");if(!adminUser){msg.textContent="Admin access is not ready.";msg.className="admin-message error";return}if(!file){msg.textContent="Choose an image first.";msg.className="admin-message error";return}const allowed=new Set(["image/jpeg","image/png","image/webp","image/gif"]);if(!allowed.has(file.type)||file.size>8*1024*1024){msg.textContent="Use JPG, PNG, WebP or GIF up to 8 MB.";msg.className="admin-message error";return}const safeName=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,"-");const r=ref(storage,`admin-content/${folder}/${Date.now()}-${safeName}`);try{const task=uploadBytesResumable(r,file,{contentType:file.type,customMetadata:{uploadedBy:adminUser.uid,folder}});await new Promise((resolve,reject)=>task.on("state_changed",s=>{msg.textContent=`Uploading ${Math.round(s.bytesTransferred/s.totalBytes*100)}%`;msg.className="admin-message"},reject,resolve));out.value=await getDownloadURL(task.snapshot.ref);msg.textContent="Upload complete. Copy the URL into the relevant content form.";msg.className="admin-message success"}catch(e){console.error(e);msg.textContent="Upload failed. Check Firebase Storage and storage.rules.";msg.className="admin-message error"}}
async function copyMedia(){const out=document.getElementById("mediaUrlOutput"),msg=document.getElementById("mediaMessage");if(!clean(out?.value)){msg.textContent="Upload an image first.";msg.className="admin-message error";return}await navigator.clipboard.writeText(out.value);msg.textContent="Image URL copied.";msg.className="admin-message success"}
async function generateSitemap(){const output=document.getElementById("sitemapOutput"),msg=document.getElementById("sitemapMessage"),origin="https://katiejae.iamkatieakaicy.workers.dev";try{msg.textContent="Generating sitemap...";const [posts,projects]=await Promise.all([getDocs(query(collection(db,"posts"),where("status","==","published"))),getDocs(query(collection(db,"projects"),where("status","==","published")))]);const paths=["/","/portfolio.html","/blog.html","/youtube.html","/books.html","/travel.html","/about.html","/social.html"],urls=new Set(paths.map(p=>origin+p));posts.docs.forEach(d=>{const s=clean(d.data().slug);if(s)urls.add(`${origin}/post.html?slug=${encodeURIComponent(s)}`)});projects.docs.forEach(d=>{const s=clean(d.data().slug);if(s)urls.add(`${origin}/project.html?slug=${encodeURIComponent(s)}`)});output.value=['<?xml version="1.0" encoding="UTF-8"?>','<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',...[...urls].sort().map(u=>`  <url><loc>${u.replaceAll("&","&amp;")}</loc></url>`),'</urlset>',''].join('\n');msg.textContent=`Generated ${urls.size} canonical URLs.`;msg.className="admin-message success"}catch(e){console.error(e);msg.textContent="Could not generate sitemap.";msg.className="admin-message error"}}
function downloadSitemap(){const output=document.getElementById("sitemapOutput"),msg=document.getElementById("sitemapMessage");if(!clean(output?.value)){msg.textContent="Generate the sitemap first.";msg.className="admin-message error";return}const blob=new Blob([output.value],{type:"application/xml;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="sitemap.xml";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);msg.textContent="sitemap.xml downloaded.";msg.className="admin-message success"}
document.getElementById("uploadMediaButton")?.addEventListener("click",uploadMedia);document.getElementById("copyMediaUrlButton")?.addEventListener("click",copyMedia);document.getElementById("generateSitemapButton")?.addEventListener("click",generateSitemap);document.getElementById("downloadSitemapButton")?.addEventListener("click",downloadSitemap);
